name: future-consulting-website

services:
  - name: wordpress
    github:
      repo: gnrz/future-consulting-website
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DB_HOST
        value: "152.42.135.76:3306"
      - key: DB_NAME
        value: wordpress
      - key: DB_USER
        value: wordpress
      - key: DB_PASSWORD
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      # Generate values from https://api.wordpress.org/secret-key/1.1/salt/
      - key: AUTH_KEY
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: SECURE_AUTH_KEY
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: LOGGED_IN_KEY
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: NONCE_KEY
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: AUTH_SALT
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: SECURE_AUTH_SALT
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: LOGGED_IN_SALT
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
      - key: NONCE_SALT
        value: "REPLACE_IN_DO_DASHBOARD"
        type: SECRET
